Exit code: 0
Wall time: 12.8 seconds
Output:
const chat=document.querySelector('#chat'),input=document.querySelector('#message'),send=document.querySelector('#send'),mic=document.querySelector('#mic'),voice=document.querySelector('#voice'),modal=document.querySelector('#modal'),modalContent=document.querySelector('#modal-content');
let voiceOn=false,isSpeaking=false,manualListening=false,micStream=null;
const profile=JSON.parse(localStorage.getItem('acola-profile')||'{"turns":0,"topics":{},"prefersShort":false,"name":""}');
const pick=a=>a[Math.floor(Math.random()*a.length)];
const themes={
  anxiety:/ansiedad|p[aÃ¢]nico|preocup|nervos|cora[cÃ§][aÃ£]o acelerado|medo|afli[cÃ§][aÃ£]o/i,
  sadness:/triste|depress|sem energia|vazio|desanim|chorar|solid[aÃ£]o/i,
  anger:/raiva|Ã³dio|odio|irritad|furios|revoltad/i,
  relationship:/namor|marid|espos|relacionamento|tÃ©rmino|termino|trai[cÃ§]|separa/i,
  work:/trabalho|emprego|chefe|carreira|faculdade|estudo|prova/i,
  grief:/luto|morreu|falec|perdi alguÃ©m|perdi alguem|saudade/i,
  sleep:/insÃ´nia|insonia|dormir|sono|acordando/i,
  selfworth:/inÃºtil|inutil|fracass|nÃ£o sou bom|nao sou bom|culpa|vergonha/i
};
const reflections={
  anxiety:['Parece que seu corpo e sua mente estÃ£o tentando antecipar algum perigo.','DÃ¡ para sentir o quanto essa preocupaÃ§Ã£o estÃ¡ ocupando espaÃ§o.','Isso soa cansativo â€” como se fosse difÃ­cil desligar o estado de alerta.'],
  sadness:['Tem um peso importante no que vocÃª estÃ¡ dizendo.','Parece que as coisas perderam um pouco da cor para vocÃª.','Obrigada por colocar em palavras algo que talvez esteja difÃ­cil de carregar.'],
  anger:['Sua raiva parece estar sinalizando que algum limite importante foi atravessado.','DÃ¡ para perceber a intensidade disso em vocÃª.','Ã€s vezes a raiva protege uma dor ou uma necessidade que nÃ£o foi ouvida.'],
  relationship:['VÃ­nculos mexem com partes muito profundas da gente.','Parece que essa relaÃ§Ã£o tem provocado sentimentos misturados.','O que aconteceu entre vocÃªs parece ter tocado num ponto sensÃ­vel.'],
  work:['Parece que essa situaÃ§Ã£o estÃ¡ cobrando muito de vocÃª.','Trabalho e estudo podem afetar bastante a forma como enxergamos nosso prÃ³prio valor.','DÃ¡ para sentir a pressÃ£o que vocÃª tem carregado.'],
  grief:['Sinto muito pela sua perda. NÃ£o existe um ritmo certo para o luto.','Essa saudade diz algo sobre a importÃ¢ncia desse vÃ­nculo.','Perder alguÃ©m pode reorganizar o mundo inteiro por dentro.'],
  sleep:['Quando o descanso falha, tudo costuma parecer mais difÃ­cil.','Seu corpo parece estar pedindo atenÃ§Ã£o e recuperaÃ§Ã£o.','Sono e emoÃ§Ãµes se alimentam mutuamente; vale olhar para os dois com cuidado.'],
  selfworth:['Estou ouvindo uma voz interna muito dura com vocÃª.','Parece que vocÃª estÃ¡ medindo seu valor por um momento muito difÃ­cil.','Culpa e vergonha podem fazer uma situaÃ§Ã£o parecer uma definiÃ§Ã£o de quem somos.'],
  general:['Estou com vocÃª nisso.','Quero acolher isso sem me apressar para dar uma soluÃ§Ã£o.','Obrigada por confiar em mim com essa parte da sua histÃ³ria.','Faz sentido que isso tenha mexido com vocÃª.']
};
const questions={
  anxiety:['O que costuma acontecer logo antes dessa sensaÃ§Ã£o comeÃ§ar?','Onde vocÃª percebe isso primeiro no corpo?','Se essa preocupaÃ§Ã£o pudesse falar, do que ela estaria tentando proteger vocÃª?','De zero a dez, qual Ã© a intensidade agora?','O que jÃ¡ ajudou, mesmo que sÃ³ um pouco, em outras vezes?'],
  sadness:['HÃ¡ quanto tempo vocÃª vem se sentindo assim?','Ainda existem pequenos momentos de alÃ­vio durante o dia?','O que ficou mais difÃ­cil de fazer ultimamente?','Tem alguÃ©m com quem vocÃª consegue dividir esse peso?','O que vocÃª sente que mais precisa agora: companhia, descanso, compreensÃ£o ou direÃ§Ã£o?'],
  anger:['Qual limite seu parece ter sido desrespeitado?','O que existe por baixo da raiva: mÃ¡goa, medo, injustiÃ§a ou outra coisa?','O que vocÃª gostaria de conseguir comunicar sem se machucar nem machucar alguÃ©m?','Essa intensidade estÃ¡ aumentando ou jÃ¡ comeÃ§ou a baixar?'],
  relationship:['O que vocÃª gostaria que essa pessoa entendesse sobre vocÃª?','Esse vÃ­nculo costuma oferecer seguranÃ§a ou deixa vocÃª em alerta?','O que Ã© responsabilidade sua e o que pertence Ã  outra pessoa?','Que conselho vocÃª daria a alguÃ©m querido vivendo a mesma situaÃ§Ã£o?'],
  work:['Qual parte pesa mais: volume, cobranÃ§a, inseguranÃ§a ou falta de sentido?','O que estÃ¡ sob seu controle hoje, mesmo que seja pequeno?','Essa pressÃ£o vem mais de fora ou da forma como vocÃª tem se cobrado?','O que seria um prÃ³ximo passo suficientemente bom, sem precisar ser perfeito?'],
  grief:['O que vocÃª mais sente falta nessa pessoa?','Existe alguma memÃ³ria que gostaria de guardar comigo agora?','Como esse luto tem aparecido no seu corpo e na sua rotina?','VocÃª tem conseguido viver essa perda acompanhado ou mais sozinho?'],
  sleep:['Sua dificuldade maior Ã© pegar no sono, continuar dormindo ou acordar sem descanso?','O que costuma passar pela sua cabeÃ§a quando vocÃª deita?','Como estÃ£o cafeÃ­na, telas e horÃ¡rios nas Ãºltimas semanas?','Isso acontece hÃ¡ quanto tempo e quantas noites por semana?'],
  selfworth:['De quem parece ser essa voz tÃ£o crÃ­tica?','Que evidÃªncia existe contra essa conclusÃ£o dura sobre vocÃª?','VocÃª falaria dessa forma com alguÃ©m de quem gosta?','O que esse erro diz sobre uma situaÃ§Ã£o â€” sem transformar isso numa definiÃ§Ã£o sua?'],
  general:['Qual parte disso estÃ¡ mais viva em vocÃª agora?','O que aconteceu logo antes de vocÃª se sentir assim?','O que vocÃª gostaria que eu entendesse melhor?','VocÃª quer ser apenas ouvido agora ou prefere pensarmos em um prÃ³ximo passo?','Como isso tem afetado sua rotina, seu corpo e seus relacionamentos?','O que vocÃª precisa e ainda nÃ£o conseguiu pedir?']
};
const risk=/suic[iÃ­]d|me matar|tirar minha vida|nÃ£o quero viver|nao quero viver|me machucar|ferir alguÃ©m|ferir alguem/i;
const anxiety=/ansiedad|p[aÃ¢]nico|preocup|nervos|cora[cÃ§][aÃ£]o acelerado/i;
const sadness=/triste|depress|sem energia|vazio|desanim/i;
function add(text,type){const el=document.createElement('div');el.className=`message ${type}`;el.textContent=text;chat.append(el);chat.scrollTop=chat.scrollHeight;if(type==='lia'&&voiceOn)speak(text)}
function reply(text){if(risk.test(text)){setTimeout(()=>{add('Obrigada por me contar. Sua seguranÃ§a vem primeiro. VocÃª corre risco imediato ou tem um plano para se machucar agora? Se sim, ligue para o SAMU no 192 ou vÃ¡ a uma emergÃªncia. Para conversar agora, ligue gratuitamente para o CVV no 188. Se puder, chame tambÃ©m uma pessoa de confianÃ§a para ficar com vocÃª.','lia');openCrisis()},500);return}profile.turns++;profile.prefersShort=(profile.prefersShort*3+(text.length<70))/4>.6;const name=text.match(/(?:me chamo|meu nome Ã©|meu nome e)\s+([A-Za-zÃ€-Ã¿]+)/i);if(name)profile.name=name[1];let topic='general';for(const [key,re] of Object.entries(themes))if(re.test(text)){topic=key;profile.topics[key]=(profile.topics[key]||0)+1;break}localStorage.setItem('acola-profile',JSON.stringify(profile));const greeting=profile.name&&profile.turns%4===0?`${profile.name}, `:'';let r=greeting+pick(reflections[topic])+' '+pick(questions[topic]);if(/nÃ£o sei|nao sei/i.test(text))r=pick(['Tudo bem nÃ£o saber ainda. Podemos ir devagar.','NÃ£o precisamos encontrar uma resposta agora. Vamos apenas notar o que aparece.'])+' '+pick(questions.general);if(/obrigad/i.test(text))r=pick(['Eu que agradeÃ§o por confiar em mim.','Fico contente por poder estar com vocÃª nisso.','VocÃª nÃ£o precisa agradecer; este espaÃ§o tambÃ©m Ã© seu.'])+' '+pick(['Quer continuar nesse assunto ou respirar um pouco?','Como vocÃª estÃ¡ se sentindo agora, comparado ao comeÃ§o?']);if(profile.turns>3&&profile.topics[topic]>2)r+=` Percebo que esse tema tem aparecido mais de uma vez; podemos observar juntos o padrÃ£o, sem tirar conclusÃµes apressadas.`;if(profile.prefersShort)r=r.split('. ').slice(0,2).join('. ');setTimeout(()=>add(r,'lia'),420+Math.min(text.length*2,500))}
function submit(){const text=input.value.trim();if(!text)return;add(text,'user');input.value='';input.style.height='auto';reply(text)}
send.onclick=submit;input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,100)+'px'});
function speak(text){speechSynthesis.cancel();isSpeaking=true;if(recognition)try{recognition.stop()}catch(e){}const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';u.rate=1.12;u.pitch=1.02;const voices=speechSynthesis.getVoices();u.voice=voices.find(v=>v.lang==='pt-BR'&&/female|francisca|maria/i.test(v.name))||voices.find(v=>v.lang==='pt-BR')||null;u.onend=u.onerror=()=>{isSpeaking=false;if(voiceOn)startRecognition()};speechSynthesis.speak(u)}
voice.onclick=async()=>{if(!voiceOn){try{micStream=micStream||await navigator.mediaDevices.getUserMedia({audio:true});voiceOn=true;voice.querySelector('b').textContent='Encerrar conversa ao vivo';voice.querySelector('small').textContent='Microfone ativo â€” fale naturalmente';speak('Estou aqui. Pode falar no seu tempo.')}catch(e){voice.querySelector('small').textContent='Permita o microfone uma vez para conversar';show('Precisamos ouvir vocÃª','<p>Autorize o microfone no aviso do navegador. Em um site publicado com HTTPS, o navegador pode lembrar sua escolha. Arquivos abertos diretamente no computador podem pedir novamente ao reabrir.</p>')}}else{voiceOn=false;voice.querySelector('b').textContent='ComeÃ§ar conversa ao vivo';voice.querySelector('small').textContent='Fale naturalmente, sem apertar Enter';speechSynthesis.cancel();isSpeaking=false;if(recognition)try{recognition.stop()}catch(e){}if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}}};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition;if(SR){recognition=new SR();recognition.lang='pt-BR';recognition.continuous=true;recognition.interimResults=true;recognition.onstart=()=>mic.classList.add('listening');recognition.onend=()=>{mic.classList.remove('listening');if(voiceOn&&!isSpeaking)setTimeout(startRecognition,250)};recognition.onerror=e=>{if(e.error==='not-allowed'){voiceOn=false;voice.querySelector('b').textContent='ComeÃ§ar conversa por voz';voice.querySelector('small').textContent='Permita o microfone para conversar';}else if(voiceOn&&!isSpeaking)setTimeout(startRecognition,500)};recognition.onresult=e=>{let interim='',final='';for(let i=e.resultIndex;i<e.results.length;i++){const part=e.results[i][0].transcript;if(e.results[i].isFinal)final+=part;else interim+=part}input.value=final||interim;if(final.trim()){manualListening=false;submit();try{recognition.stop()}catch(err){}}};mic.onclick=()=>{manualListening=true;startRecognition()}}else{mic.onclick=voice.onclick=()=>alert('O reconhecimento de voz nÃ£o estÃ¡ disponÃ­vel neste navegador. Tente usar Chrome ou Edge.')}
function startRecognition(){if(recognition&&!isSpeaking)try{recognition.start()}catch(e){}}
function show(title,html){modalContent.innerHTML=`<h2>${title}</h2>${html}`;modal.showModal()}
function openCrisis(){show('VocÃª nÃ£o precisa passar por isso sÃ³','<p>Se houver perigo imediato, ligue para o <strong>SAMU (192)</strong>, para a emergÃªncia local ou vÃ¡ ao pronto atendimento.</p><p>O <strong>CVV atende pelo 188</strong>, gratuitamente, 24 horas. Se for seguro, avise uma pessoa de confianÃ§a e nÃ£o fique sÃ³.</p><p><a href="tel:188">Ligar para o CVV â€” 188</a></p>')}
document.querySelectorAll('[data-crisis]').forEach(b=>b.onclick=openCrisis);document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>b.dataset.open==='about'?show('Como a AcolÃ¡ funciona','<p>A Lia oferece escuta, organizaÃ§Ã£o de pensamentos, psicoeducaÃ§Ã£o e exercÃ­cios de bem-estar. QuestionÃ¡rios podem indicar que uma avaliaÃ§Ã£o profissional Ã© recomendada, mas nÃ£o geram diagnÃ³stico clÃ­nico.</p><p>O protÃ³tipo atual usa recursos do prÃ³prio navegador. A versÃ£o de produÃ§Ã£o deverÃ¡ ter revisÃ£o clÃ­nica, testes de seguranÃ§a e encaminhamento humano.</p>'):show('Privacidade desde o comeÃ§o','<p>Neste protÃ³tipo, as mensagens nÃ£o sÃ£o enviadas a um servidor nem armazenadas. Em produÃ§Ã£o, memÃ³ria e histÃ³rico serÃ£o opcionais, com consentimento claro, exclusÃ£o fÃ¡cil e proteÃ§Ã£o compatÃ­vel com a LGPD.</p>'));document.querySelector('.close').onclick=()=>modal.close();modal.onclick=e=>{if(e.target===modal)modal.close()};

